---
title: "Reading data from the web"
output: github_document
date: "2025-10-09"
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(rvest)
library(httr)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal()+theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridis",
   ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Scrape a table

I want the first table from [this page](https://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm)


read in the html

```{r}
url = "https://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(url)
```

extract the table(s); focus on  the first one

```{r}
tabl_marj = 
  drug_use_html %>%
  html_nodes(css = "table") %>%
  .[[1]] %>%
  html_table() %>%
  slice(-1) %>%
  as_tibble()
```



## Star War Movie info

I want the data from [here](https://www.imdb.com/list/ls070150896/).

```{r}
url = "https://www.imdb.com/list/ls070150896/"

swm_html = read_html(url)
```

Grab elements that I want

```{r}
title_vec = 
  swm_html %>%
  html_nodes(css = ".ipc-title-link-wrapper .ipc-title__text--reduced") %>%
  html_text()

runtime_vec = 
  swm_html %>%
  html_nodes(css = ".dli-title-metadata-item:nth-child(2)") %>%
  html_text()


swm_df = 
  tibble(
    title = title_vec,
    runtime = runtime_vec)
```


## Get some water data

This is coming from an API

```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>%
  content("parsed")

nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>%
  content("text") %>%
  jsonlite::fromJSON() %>%
  as_tibble()
```



## BRFSS

Some process, different data

```{r}
brfss_2010 =
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit"=5000)) %>%
  content("parsed")
```






